version: '3.7'

services:
    backend:
        build:
            context: ./workshop-backend
            dockerfile: ./Dockerfile
        ports:
            - 9000:9000
        environment:
            PORT: 9000
            DB_HOST: host.docker.internal
            DB_PORT: 27017
        volumes:
            - ./workshop-backend/:/app
    frontend:
        build:
            context: ./workshop-frontend
            dockerfile: ./Dockerfile
        ports:
            - 3000:80
        environment:
            API_URL: host.docker.internal:9000            
        volumes:
            - ./workshop-frontend/:/app
    job:
        build:
            context: ./workshop-etl
            dockerfile: ./workshop-etl/Dockerfile
  
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: P@ssword11

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: P@ssword11

    mysql:        
        image: 'mysql:5.7'
        environment:            
            MYSQL_DATABASE: Consumer
            MYSQL_USER: admin
            MYSQL_PASSWORD: Password11      
            MYSQL_ROOT_PASSWORD: Password11   
        ports: 
            - 3306:3306 